"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { authClient } from "@/lib/auth-client";

export default function SignInPage() {
  const router = useRouter(); const [register, setRegister] = useState(false); const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); try { const form = new FormData(event.currentTarget); const email = String(form.get("email")); const password = String(form.get("password")); const result = register ? await authClient.signUp.email({ name:String(form.get("name")), email, password }) : await authClient.signIn.email({ email, password }); if (result.error) return setError(result.error.message ?? "Account setup is unavailable. Confirm the database and authentication configuration."); if (register) { const onboarding = await fetch("/api/onboarding/patient", { method:"POST" }); if (!onboarding.ok) return setError("Account created, but patient profile setup failed. Please sign in again."); } router.replace("/"); router.refresh(); } catch { setError("Cannot reach the secure account service. Confirm the app is running and the database is configured."); } finally { setPending(false); } }
  return <main className="auth-page"><section className="auth-card"><a className="auth-brand" href="/"><span>G</span> Gluco<b>Link</b></a><p className="eyebrow">SECURE CARE PORTAL</p><h1>{register ? "Create your patient account" : "Welcome back"}</h1><p className="auth-copy">{register ? "Start securely tracking your glucose and sharing it with your care team." : "Sign in to access your health record."}</p><form onSubmit={submit}>{register && <label>Full name<input required minLength={2} name="name" autoComplete="name" /></label>}<label>Email address<input required type="email" name="email" autoComplete="email" /></label><label>Password<input required type="password" minLength={12} name="password" autoComplete={register ? "new-password" : "current-password"} /><small>At least 12 characters.</small></label>{error && <p className="auth-error" role="alert">{error}</p>}<button disabled={pending} className="auth-submit">{pending ? "Please wait…" : register ? "Create account" : "Sign in"}</button></form><button className="auth-switch" onClick={() => { setRegister(!register); setError(""); }}>{register ? "Already have an account? Sign in" : "New to GlucoLink? Create an account"}</button><p className="auth-privacy">By continuing, you agree to the Terms and acknowledge the Privacy Notice.</p></section></main>;
}
