"use client";

import { FormEvent, useMemo, useState } from "react";
import { analytics, trend } from "@/features/glucose/analytics";
import { seedReadings, type GlucoseReading, type MealContext } from "@/features/glucose/types";

const contextNames: Record<MealContext, string> = { FASTING: "Fasting", BEFORE_MEAL: "Before meal", AFTER_MEAL: "After meal", BEDTIME: "Bedtime", RANDOM: "Random" };
const points = "12,142 84,128 156,136 228,106 300,121 372,83 444,99 516,72 588,86";

export function Dashboard() {
  const [readings, setReadings] = useState(seedReadings);
  const [open, setOpen] = useState(false);
  const [mode, setMode] = useState<"patient" | "clinical">("patient");
  const stats = useMemo(() => analytics(readings), [readings]);
  const current = readings.at(-1)!;
  const currentTrend = trend(readings);
  function save(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const form = new FormData(e.currentTarget); const value = Number(form.get("value"));
    if (!Number.isInteger(value) || value < 20 || value > 700) return;
    setReadings((prev) => [...prev, { id: crypto.randomUUID(), value, context: form.get("context") as MealContext, source: "MANUAL", verified: false, recordedAt: new Date().toISOString() }]); setOpen(false);
  }
  return <main className="shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">G</span><span>Gluco<span>Link</span></span></div><div className="workspace"><span className="avatar">SA</span><div><b>Sarah Adams</b><small>Patient workspace</small></div></div><nav><a className="active">⌂ <span>Overview</span></a><a>▣ <span>My readings</span></a><a>◴ <span>History</span></a><a>♡ <span>Care plan</span></a><a>▤ <span>Messages</span><i>2</i></a><a>◌ <span>Devices</span></a></nav><div className="side-bottom"><a>⚙ <span>Settings</span></a><button className="mode" onClick={() => setMode(mode === "patient" ? "clinical" : "patient")}>⇄ {mode === "patient" ? "Clinician preview" : "Patient preview"}</button><p>© 2026 GlucoLink<br/>Privacy & security</p></div></aside>
    <section className="content"><header><div><p className="eyebrow">SATURDAY, JULY 26</p><h1>Good evening, Sarah <span>✦</span></h1><p className="sub">Here’s how your glucose is looking today.</p></div><div className="header-actions"><button className="icon-btn" aria-label="Notifications">♧<b></b></button><button className="profile">SA</button></div></header>
      <section className="hero-grid"><article className="glucose-card"><div className="card-top"><div><p className="label">CURRENT GLUCOSE</p><div className="reading"><strong>{current.value}</strong><span>mg/dL</span></div><span className="status good">● In range</span></div><div className="trend"><span className={currentTrend}>↗</span><small>Since last reading</small><b>+7 mg/dL</b></div></div><div className="range"><div className="range-track"><span></span><i></i></div><div><small>70</small><small>Target range 70–180</small><small>180</small></div></div><p className="reading-note">Last recorded at 7:30 PM · Before dinner</p></article><article className="quick-card"><div><p className="label">QUICK ACTIONS</p><h2>Keep your care team in the loop.</h2></div><div className="quick-actions"><button onClick={() => setOpen(true)}><span>＋</span> Log reading</button><button><span>⇣</span> Import device</button><button><span>▣</span> Message care team</button></div></article></section>
      <section className="section-heading"><div><h2>Glucose overview</h2><p>Your readings over the last 7 days</p></div><button className="select">Last 7 days⌄</button></section>
      <article className="chart-card"><div className="chart-meta"><div><b>128 <small>mg/dL</small></b><span>Daily average</span></div><div className="legend"><i></i> In range <em></em> Above range</div></div><div className="chart"><div className="target-zone"></div><svg viewBox="0 0 600 170" preserveAspectRatio="none" aria-label="Glucose line chart"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#44c59a" stopOpacity=".22"/><stop offset="1" stopColor="#44c59a" stopOpacity="0"/></linearGradient></defs><polygon points={points + " 588,170 12,170"} fill="url(#fill)"/><polyline points={points} fill="none" stroke="#24a77c" strokeWidth="3" strokeLinejoin="round"/>{["12,142","84,128","156,136","228,106","300,121","372,83","444,99","516,72","588,86"].map((p) => { const [cx, cy] = p.split(","); return <circle key={p} cx={cx} cy={cy} r="4" fill="white" stroke="#24a77c" strokeWidth="3"/>; })}</svg><div className="axis"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div></article>
      <section className="metrics"><Metric label="TIME IN RANGE" value={`${stats.tir}%`} note="Above your 70% goal" tone="green"/><Metric label="ESTIMATED A1C" value={`${stats.a1c}%`} note="Based on recent readings" tone="blue"/><Metric label="HIGH EVENTS" value={stats.highEvents.toString()} note="No events in the last 24h" tone="amber"/><Metric label="VARIABILITY" value={`${stats.cv}%`} note="Target is below 36%" tone="purple"/></section>
      <section className="lower-grid"><article className="list-card"><div className="card-title"><div><h2>Today’s readings</h2><p>5 readings recorded</p></div><button>View history →</button></div>{readings.slice(-4).reverse().map((r) => <div className="reading-row" key={r.id}><span className="reading-dot"></span><div><b>{contextNames[r.context]}</b><small>{new Date(r.recordedAt).toLocaleTimeString([], {hour:"numeric", minute:"2-digit"})} · {r.source === "DEVICE_IMPORT" ? "Device import" : "Manual"}</small></div><strong>{r.value} <small>mg/dL</small></strong></div>)}</article><article className="care-card"><div className="care-top"><span className="pill">NEXT UP</span><button>•••</button></div><h2>Evening Metformin</h2><p>500 mg · Take with dinner</p><div className="care-footer"><span>◷ Scheduled for 8:00 PM</span><button>Mark taken</button></div></article></section>
    </section>
    {open && <div className="modal-backdrop"><form className="modal" onSubmit={save}><button type="button" className="close" onClick={() => setOpen(false)}>×</button><p className="eyebrow">NEW READING</p><h2>Log blood glucose</h2><label>Glucose value <div className="input-wrap"><input name="value" required type="number" min="20" max="700" autoFocus/><span>mg/dL</span></div></label><label>When was this taken?<select name="context" defaultValue="BEFORE_MEAL">{Object.entries(contextNames).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></label><button className="submit">Save reading</button><p className="disclaimer">This is for tracking and care coordination, not emergency guidance.</p></form></div>}
  </main>;
}
function Metric({label,value,note,tone}:{label:string;value:string;note:string;tone:string}) { return <article className="metric"><div className={`metric-icon ${tone}`}>⌁</div><p className="label">{label}</p><b>{value}</b><span>{note}</span></article>; }
